object IsoPackager {
    fun getIsoFieldMap() = listOf(
        IsoField(0, 4, true, "Message Type Indicator", FieldType.NUMERIC),
        IsoField(1, 16, true, "Bit Map", FieldType.BINARY),
        IsoField(2, 19, false, "PAN", FieldType.NUMERIC),
        IsoField(3, 6, true, "Processing Code", FieldType.NUMERIC),
        IsoField(4, 12, true, "Transaction Amount", FieldType.NUMERIC),
        IsoField(5, 12, true, "Settlement Amount", FieldType.NUMERIC),
        IsoField(6, 12, true, "Amount, Cardholder Billing", FieldType.NUMERIC),
        IsoField(7, 10, true, "Transmission Date & Time", FieldType.NUMERIC),
        IsoField(8, 8, true, "Amount, Cardholder Billing Fee", FieldType.NUMERIC),
        IsoField(9, 8, true, "Convertion Rate, Settlement", FieldType.NUMERIC),
        IsoField(10, 8, true, "Convertion Rate, Cardholder Billing", FieldType.NUMERIC),
        IsoField(11, 6, true, "System Trace Audit Number (STAN)", FieldType.NUMERIC),
        IsoField(12, 6, true, "Local Transaction Time (hhmmss)", FieldType.NUMERIC),
        IsoField(13, 4, true, "Local Transaction Date (MMDD)", FieldType.NUMERIC),
        IsoField(14, 4, true, "Expiration Date (YYMM)", FieldType.NUMERIC),
        IsoField(15, 4, true, "Settlement Date", FieldType.NUMERIC),
        IsoField(16, 4, true, "Currency Convertion Date", FieldType.NUMERIC),
        IsoField(17, 4, true, "Capture Date", FieldType.NUMERIC),
        IsoField(18, 4, true, "Merchant Type / Merchant Category Code", FieldType.NUMERIC),
        IsoField(19, 3, true, "Acquiring Institution (Country Code)", FieldType.NUMERIC),
        IsoField(20, 3, true, "PAN Extended (Country Code)", FieldType.NUMERIC),
        IsoField(21, 3, true, "Forwarding Institution (Country Code)", FieldType.NUMERIC),
        IsoField(22, 3, true, "Point of Sale (POS) Entry Mode", FieldType.NUMERIC),
        IsoField(23, 3, true, "Application PAN Sequence Number", FieldType.NUMERIC),
        IsoField(24, 3, true, "Function code (ISO 8583:1993), or network international identifier (NII)", FieldType.NUMERIC),
        IsoField(25, 2, true, "Point of service condition code", FieldType.NUMERIC),
        IsoField(26, 2, true, "Point of service capture code", FieldType.NUMERIC),
        IsoField(27, 1, true, "Authorizing identification response length", FieldType.NUMERIC),
        IsoField(28, 8, true, "Amount, transaction fee", FieldType.NUMERIC_D_C),
        IsoField(29, 8, true, "Amount, settlement fee", FieldType.NUMERIC_D_C),
        IsoField(30, 8, true, "Amount, transaction processing fee", FieldType.NUMERIC_D_C),
        IsoField(31, 8, true, "Amount, settlement processing fee", FieldType.NUMERIC_D_C),
        IsoField(32, 11, false, "Acquiring institution identification code", FieldType.NUMERIC),
        IsoField(33, 11, false, "Forwarding institution identification code", FieldType.NUMERIC),
        IsoField(34, 28, false, "Primary account number, extended", FieldType.NUMERIC_S),
        IsoField(35, 37, false, "Track 2 Data", FieldType.ALPHANUMERIC_S),
        IsoField(36, 104, false, "Track 3 Data", FieldType.NUMERIC),
        IsoField(37, 12, true, "Retrieval Reference Number", FieldType.ALPHANUMERIC),
        IsoField(38, 6, true, "Authorization identification response", FieldType.ALPHANUMERIC),
        IsoField(39, 2, true, "Response Code", FieldType.ALPHANUMERIC),
        IsoField(40, 3, true, "Service Restriction Code", FieldType.ALPHANUMERIC),
        IsoField(41, 8, true, "Card acceptor terminal identification", FieldType.ALPHANUMERIC_S),
        IsoField(42, 15, true, "Card acceptor identification code", FieldType.ALPHANUMERIC_S),
        IsoField(43, 40, true, "Card acceptor name/location (1–25 card acceptor name or automated teller machine (ATM) location, 26-38 city name, 39-40 country code)", FieldType.ALPHANUMERIC_S),
        IsoField(44, 25, false, "Additional response data", FieldType.ALPHANUMERIC),
        IsoField(45, 76, false, "Track 1 data", FieldType.ALPHANUMERIC),
        IsoField(46, 999, false, "Additional data (ISO)", FieldType.ALPHANUMERIC),
        IsoField(47, 999, false, "Additional data (national)", FieldType.ALPHANUMERIC),
        IsoField(48, 999, false, "Additional data (private)", FieldType.ALPHANUMERIC),
        IsoField(49, 3, true, "Currency Code, Transaction", FieldType.ALPHANUMERIC),
        IsoField(50, 3, true, "Currency Code, Settlement", FieldType.ALPHANUMERIC),
        IsoField(51, 3, true, "Currency Code, Cardholder Billing", FieldType.ALPHANUMERIC),
        IsoField(52, 64, true, "PIN Block", FieldType.BINARY),
        IsoField(53, 16, true, "Security related control information", FieldType.NUMERIC),
        IsoField(54, 120, false, "Additional amounts", FieldType.ALPHANUMERIC),
        IsoField(55, 999, false, "ICC Data - EMV Tags", FieldType.ALPHANUMERIC_S),
        IsoField(56, 999, false, "Reserved (ISO)", FieldType.ALPHANUMERIC_S),
        IsoField(57, 999, false, "Reserved (national)", FieldType.ALPHANUMERIC_S),
        IsoField(58, 999, false, "Reserved (national)", FieldType.ALPHANUMERIC_S),
        IsoField(59, 999, false, "Reserved (national)", FieldType.ALPHANUMERIC_S),
        IsoField(60, 999, false, "Reserved (national)", FieldType.ALPHANUMERIC_S),
        IsoField(61, 999, false, "Reserved (private) (e.g. CVV2/service code   transactions)", FieldType.ALPHANUMERIC_S),
        IsoField(62, 999, false, "Reserved (private) (e.g. transactions: invoice number, key exchange transactions: TPK key, etc.)", FieldType.ALPHANUMERIC_S),
        IsoField(63, 999, false, "Reserved (private)", FieldType.ALPHANUMERIC_S),
        IsoField(64, 64, true, "Message authentication code (MAC)", FieldType.BINARY),
    )
}

data class IsoField(
    val id: Int,
    val length: Int,
    val fixed: Boolean,
    val name: String,
    val type: FieldType
)

enum class FieldType {
    BINARY,
    NUMERIC,
    NUMERIC_D_C,
    NUMERIC_S,
    ALPHANUMERIC,
    ALPHANUMERIC_S
}